# Generated by Django 2.0.4 on 2018-05-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Inicio')),
                ('imagem', models.ImageField(upload_to='cursos/imagens', verbose_name='Imagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
