# Generated by Django 2.0.4 on 2018-05-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/imagens', verbose_name='Imagem'),
        ),
    ]
