# Generated by Django 2.0.4 on 2018-05-01 23:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ('cursos', '0002_auto_20180501_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nome'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelManagers(
            name='curso',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='about',
            field=models.TextField(blank=True, verbose_name='Sobre'),
        ),
    ]
